In [3]:
# This practice of replacing explicit loops with array expressions is
# referred to by some people vectorization
import numpy as np

# Expressing Conditional Logic as Array Operations

In [4]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [6]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
# The second and third arguments to np.where don’t need to be arrays; one or both of them can be scalars
arr = np.random.standard_normal((4, 4))
arr

array([[-0.26606687, -0.22252618, -2.01757529,  2.18610773],
       [ 0.30783624,  1.67779953,  0.93921049,  0.21083356],
       [ 1.40911062,  0.22255947,  0.73181359,  0.943061  ],
       [-0.33723758, -0.93538426,  0.28887787,  0.14163598]])

In [10]:
arr > 0

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True]])

In [11]:
np.where(arr > 0,2,-2)

array([[-2, -2, -2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2, -2,  2,  2]])

In [13]:
np.where(arr > 0,2,arr) #  set only positive values to 2

array([[-0.26606687, -0.22252618, -2.01757529,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.33723758, -0.93538426,  2.        ,  2.        ]])

# Mathmatical and Statistical Methods

In [14]:
arr = np.random.standard_normal((5, 4))
arr

array([[-0.31217889, -2.05296886, -0.38392427, -1.65608493],
       [-1.17336761, -1.30563143,  0.71750909,  1.0968905 ],
       [ 1.27007902,  0.3176228 , -1.13034754, -1.1498476 ],
       [-0.74155322,  0.08375449, -2.28940769, -0.56607285],
       [-0.36103449,  0.32465798,  0.92800555, -0.29348175]])

In [15]:
arr.mean()

-0.4338690843967951

In [20]:
arr.mean(axis=1) #
# Here, arr.mean(1) (which is the same as arr.mean(axis=1))

array([-1.10128924, -0.16614986, -0.17312333, -0.87831982,  0.14953682])

In [19]:
arr.mean(axis=0) # Returns the average of the array elements along axis 0.
# axis 0 is vertical , axis 1 is horizontal

array([-0.26361104, -0.526513  , -0.43163297, -0.51371932])

In [21]:
arr.mean?

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method

# Methods for Boolean Arrays

In [22]:
arr = np.random.standard_normal(10)
arr

array([-0.28930263,  0.24222237,  0.89044664, -0.34681121, -1.36503649,
        0.67472355, -0.04376168, -1.98716412, -0.14610451, -0.14315188])

In [23]:
arr > 0

array([False,  True,  True, False, False,  True, False, False, False,
       False])

In [24]:
(arr > 0).sum()

3

In [25]:
(arr > 0 ).any()

True

In [26]:
(arr > 0 ).all()

False

# Sorting

In [27]:
arr = np.random.standard_normal((5, 3))
arr

array([[-0.68793335, -1.2712326 ,  0.70132403],
       [ 0.4217717 ,  1.67006442, -0.98256548],
       [ 0.39878714,  0.24823381, -0.86223833],
       [-0.09087728,  0.71458961,  0.18824812],
       [-0.26013219,  2.35743459, -0.80008176]])

In [30]:
arr.sort(1)
arr # sort along axis 1

array([[-1.2712326 , -0.68793335,  0.70132403],
       [-0.98256548,  0.4217717 ,  1.67006442],
       [-0.86223833,  0.24823381,  0.39878714],
       [-0.09087728,  0.18824812,  0.71458961],
       [-0.80008176, -0.26013219,  2.35743459]])

In [32]:
sorted_arr2 = np.sort(arr)
sorted_arr2 # The top-level method np.sort returns a sorted copy of an array instead of
# modifying the array in-place

array([[-1.2712326 , -0.68793335,  0.70132403],
       [-0.98256548,  0.4217717 ,  1.67006442],
       [-0.86223833,  0.24823381,  0.39878714],
       [-0.09087728,  0.18824812,  0.71458961],
       [-0.80008176, -0.26013219,  2.35743459]])

# Unique and Other Set Logic

In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
np.unique(names)
#  A commonly used one is np.unique, which returns the sorted unique values in an array:

array(['Bob', 'Joe', 'Will'], dtype='<U4')