In [1]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [2]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [3]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [4]:
x @ np.ones(3) # The @ symbol (as of Python 3.5) also works as an infix operator that
# performs matrix multiplication

array([ 6., 15.])

In [5]:
# numpy.linalg has a standard set of matrix decompositions and things
# like inverse and determinant

In [6]:
from numpy.linalg import inv, qr# linear algebra

In [8]:
x = np.random.standard_normal((5,5))

In [10]:
mat = x.T.dot(x)
inv(mat)

array([[ 6.83244269,  3.96921247,  4.9639723 , -7.83558989, -1.20914738],
       [ 3.96921247,  2.57906446,  2.90025913, -4.50890229, -0.52828506],
       [ 4.9639723 ,  2.90025913,  4.03440418, -5.84516425, -0.94218595],
       [-7.83558989, -4.50890229, -5.84516425,  9.33832519,  1.55865474],
       [-1.20914738, -0.52828506, -0.94218595,  1.55865474,  0.52099855]])

In [11]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.49880108e-15,  4.49640325e-15,
        -4.99600361e-16,  8.32667268e-17],
       [ 5.32907052e-15,  1.00000000e+00,  8.88178420e-16,
         1.77635684e-15,  4.44089210e-16],
       [-1.13797860e-15, -1.11022302e-15,  1.00000000e+00,
        -1.99840144e-15,  2.22044605e-16],
       [ 4.44089210e-16,  4.21884749e-15,  2.22044605e-15,
         1.00000000e+00, -4.44089210e-16],
       [-3.55271368e-15,  4.44089210e-16, -8.88178420e-16,
         0.00000000e+00,  1.00000000e+00]])

In [12]:
q, r = qr(mat)
# QR decomposition is a technique used to convert a matrix into the form A = QR, where R equals upper triangular matrix, 
# Q equals orthogonal matrix, and Q^(T)Q=I holds, where Q^(T) is the Qs' transpose, and I is the matrixs' identity.

In [13]:
r

array([[-7.30858791,  4.13518114, -0.27627799, -4.26374232, -0.56276656],
       [ 0.        , -6.97904672,  0.23947923, -4.68787559,  8.52007206],
       [ 0.        ,  0.        , -3.08440116, -2.06715976,  0.57826288],
       [ 0.        ,  0.        ,  0.        , -0.47046785,  2.88925882],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.43316105]])

In [14]:
q

array([[-0.80412789, -0.08230327,  0.18732914,  0.1928534 , -0.52375554],
       [ 0.37638134, -0.6687133 ,  0.06957111,  0.5949413 , -0.22883251],
       [ 0.05135675,  0.09902262, -0.90566375,  0.02774279, -0.40811825],
       [-0.45651103, -0.42901162, -0.37366648,  0.10997519,  0.67514852],
       [-0.02599201,  0.59345787, -0.0146348 ,  0.77200273,  0.22567628]])

In [15]:
q.dot(q.T)

array([[ 1.00000000e+00,  4.16333634e-17,  2.77555756e-17,
        -1.66533454e-16, -1.24900090e-16],
       [ 4.16333634e-17,  1.00000000e+00, -1.38777878e-17,
         2.77555756e-17, -6.24500451e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00,
        -1.66533454e-16, -4.16333634e-17],
       [-1.66533454e-16,  2.77555756e-17, -1.66533454e-16,
         1.00000000e+00,  2.77555756e-17],
       [-1.24900090e-16, -6.24500451e-17, -4.16333634e-17,
         2.77555756e-17,  1.00000000e+00]])