In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr * 2
%timeit [i * 2 for i in my_list]

827 µs ± 38.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
51.9 ms ± 523 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
arr1.shape % one dimension

(5,)

In [8]:
arr1.dtype # a dtype, an object describing the data type of the array:

dtype('float64')

In [20]:
data0 = [[6,7.5,8,0,1]] # two dimensions
arr0 = np.array(data0)
arr0.shape # Every array has a shape,a tuple indicating the size of each dimension

(1, 5)

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim % 

2

In [12]:
arr2.shape

(2, 4)

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.arange(15) # Since NumPy is focused on numerical computing, the data type, if not specified,
# will in many cases be float64 (floating point).

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
arr2 = arr2.astype(np.float64) # You can explicitly convert or cast an array from one dtype to another using
# ndarray’s astype method
arr2

array([1., 2., 3.])

In [28]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
arr_slice = arr[5:8]
arr_slice[:] = 100
arr # An important first distinction from Python’s built-in lists is that
#array slices are views on the original array. This means that the data is not
#copied, and any modifications to the view will be reflected in the source array

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [32]:
arr_slice = arr[5:8].copy() # If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the
# array—for example, arr[5:8].copy().
arr_slice = 200
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2] # In multidimensional arrays, if you omit later indices, the returned object
# will be a lower dimensional ndarray consisting of all the data along the higher dimensions

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0,2]

3

# Indexing with slices

In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d.shape #  2 × 2 × 3 array arr3d

(2, 2, 3)

In [42]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr3d[1,0] # arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array

array([7, 8, 9])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr2d.shape

(3, 3)

In [48]:
arr2d[:2] #  It can be helpful to read the
# expression arr2d[:2] as “select the first two rows of arr2d.”

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr2d[:,1:] # ':' represents 'begin : end'

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
arr2d[:,:1] # . Note that a colon by itself means to take the entire axis

array([[1],
       [4],
       [7]])

In [52]:
arr2d[:2,2]

array([3, 6])

In [53]:
arr2d[:2,1:2] # equals arr2d[:2,1]

array([[2],
       [5]])

In [55]:
arr2d[:2,1:2].shape

(2, 1)

In [54]:
arr2d[:2,1]

array([2, 5])

In [56]:
arr2d[:2,1].shape

(2,)

# Bollean Indexing

In [57]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will',
'Joe', 'Joe'])
data = np.random.standard_normal((7, 4)) # use here the standard_normal function in 
# numpy.random to generate some random normally distributed data:

In [58]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [59]:
data

array([[ 0.34924006, -1.40741883,  1.93900025, -0.03237347],
       [-1.69984969,  0.16156403,  2.08340409,  0.58572601],
       [-0.02499844, -0.77882747,  0.32687141, -0.59141573],
       [ 1.61982355, -0.37680411,  1.08669683, -0.25576096],
       [ 0.36574586, -0.38408763, -1.09664192, -0.57895925],
       [-0.94029326,  0.51999549, -0.7879352 , -0.0718731 ],
       [-0.17692865, -0.38802897, -0.83305585,  0.98810387]])

In [62]:
names == 'Bob' #  Like arithmetic
# operations, comparisons (such as ==) with arrays are also vectorized

array([ True, False, False,  True, False, False, False])

In [64]:
data[names == 'Bob'] # The boolean array must be of the same length as the array axis it’s indexing.

array([[ 0.34924006, -1.40741883,  1.93900025, -0.03237347],
       [ 1.61982355, -0.37680411,  1.08669683, -0.25576096]])

In [65]:
data[names == 'Bob',2:]

array([[ 1.93900025, -0.03237347],
       [ 1.08669683, -0.25576096]])

In [66]:
data[names == 'Bob',3]

array([-0.03237347, -0.25576096])

In [69]:
data[names == 'Bob'].shape

(2, 4)

In [71]:
data[names == 'Bob'][0]

array([ 0.34924006, -1.40741883,  1.93900025, -0.03237347])

In [72]:
data[names == 'Bob'][:,2:] # equals to data[names == 'Bob',2:]

array([[ 1.93900025, -0.03237347],
       [ 1.08669683, -0.25576096]])

In [73]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [75]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [77]:
data[data < 0] = 0
data

array([[0.34924006, 0.        , 1.93900025, 0.        ],
       [0.        , 0.16156403, 2.08340409, 0.58572601],
       [0.        , 0.        , 0.32687141, 0.        ],
       [1.61982355, 0.        , 1.08669683, 0.        ],
       [0.36574586, 0.        , 0.        , 0.        ],
       [0.        , 0.51999549, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.98810387]])

# Fancy Indexing

In [79]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
arr[[4,3,0,6]] # To select out a subset of the rows in a particular order, you can simply pass
# a list or ndarray of integers specifying the desired order

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr[[-1]] #  Using negative indices selects rows from the end:

array([[7., 7., 7., 7.]])

In [87]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr[[1,5,7,2],[0,3,1,2]] # Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected

array([ 4, 23, 29, 10])

In [94]:
arr[[1,5,7,2]][:,[0,3,1,2]] # (arr[[1,5,7,2]])[:,[0,3,1,2]] 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [96]:
# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array

# Transposing Arrays and Swapping Axes

In [97]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
arr.T # Arrays have the transpose method and also the special T attribute

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [100]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [102]:
arr = np.random.standard_normal((6,3))
arr

array([[ 1.51208817, -0.37308908, -0.03369174],
       [-0.56935743, -0.53182137,  0.40418295],
       [-0.77557135,  0.55838555,  0.99947033],
       [ 0.46928605,  0.47837887, -1.24214595],
       [ 1.13970163, -0.10099876, -1.08871502],
       [ 0.12824368, -0.30073809,  0.53473851]])

In [103]:
np.dot(arr.T,arr) # computing the inner matrix product using np.dot

array([[ 4.74768506, -0.62359464, -2.81138522],
       [-0.62359464,  1.06331435, -0.28936707],
       [-2.81138522, -0.28936707,  4.17761217]])

In [105]:
arr.T @ arr # The @ infix operator is another way to do matrix multiplication:

array([[ 4.74768506, -0.62359464, -2.81138522],
       [-0.62359464,  1.06331435, -0.28936707],
       [-2.81138522, -0.28936707,  4.17761217]])

In [108]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [110]:
arr.transpose(1,0,2) # Here, the axes have been reordered with the second axis first, the first axis
#second, and the last axis unchanged
# While it can be difficult to visualize a
# multidimensional transposition, it is a “reorientation” of the array which
# does not result in any data being copied or moved around

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [113]:
arr.shape

(2, 2, 4)

In [114]:
arr.swapaxes(1,2) # ndarray has the method swapaxes, which takes a pair of axis numbers and switches
# the indicated axes to rearrange the data:

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [115]:
arr.swapaxes(1,2).shape

(2, 4, 2)